# Generated by Django 2.1.3 on 2018-11-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('is_married', models.BooleanField(blank=True, verbose_name='Est marié(e) ?')),
                ('number_of_children', models.PositiveSmallIntegerField(verbose_name="Nombre d'enfants")),
                ('department', models.CharField(choices=[('I', 'IT')], max_length=1, verbose_name='Département')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
