# Generated by Django 2.1.3 on 2018-11-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_married',
            field=models.BooleanField(blank=True, default=False, verbose_name='Est marié(e) ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Nombre d'enfants"),
        ),
    ]
