# Generated by Django 2.1.3 on 2018-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20181115_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canton',
            field=models.CharField(default='', max_length=64, verbose_name='Canton'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=64, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fax',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='npa',
            field=models.SmallIntegerField(default=1234, verbose_name='NPA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='', max_length=128, verbose_name='Street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('A', 'Area manager'), ('I', 'IT'), ('M', 'Market'), ('R', 'Human Resources')], max_length=1, verbose_name='Département'),
        ),
    ]
