# Generated by Django 2.1.3 on 2018-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20181122_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('A', 'Area manager'), ('I', 'IT'), ('M', 'Market'), ('P', 'Pharmacist manager'), ('R', 'Human Resources')], max_length=1, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fax',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
