# Generated by Django 2.1.3 on 2018-11-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20181115_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbench',
            name='category',
            field=models.CharField(choices=[('C', 'Central work'), ('J', 'Justified absence'), ('T', 'Travel'), ('V', 'Vacation')], max_length=1, verbose_name='Category'),
        ),
    ]
