# Generated by Django 2.1.3 on 2018-11-15 08:43

from django.db import migrations, models
import django.db.models.deletion
import timesheet.models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20181115_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpanseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('M', 'Meal'), ('T', 'Travel'), ('H', 'Hotel'), ('O', 'Other')], max_length=1, verbose_name='Category')),
                ('details', models.TextField(help_text='Enter the informations like total km, expense meal, etc.', verbose_name='Details')),
                ('justificatif', models.FileField(upload_to=timesheet.models.user_directory_path, verbose_name='Justificatif')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Timesheet')),
            ],
        ),
    ]
