# Generated by Django 2.1.3 on 2018-11-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_expansereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansereport',
            name='details',
            field=models.CharField(help_text='Enter the informations like total km, expense meal, etc.', max_length=255, verbose_name='Details'),
        ),
    ]
