# Generated by Django 2.1.3 on 2018-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0013_auto_20181116_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='duration_work',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='is_all_day_work',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='allDay',
            field=models.BooleanField(blank=True, default=False, verbose_name='All day'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='end_time',
            field=models.TimeField(default='14:00:00'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='hours',
            field=models.TimeField(default='08:30:00', editable=False, verbose_name='Duration work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
