# Generated by Django 2.1.3 on 2018-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_auto_20181116_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.TimeField(verbose_name='Duration work'),
        ),
    ]
