# Generated by Django 2.1.3 on 2018-11-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0015_auto_20181116_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.DurationField(verbose_name='Duration work'),
        ),
    ]
