# Generated by Django 2.1.3 on 2018-11-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0018_auto_20181119_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.TimeField(verbose_name='Duration work'),
        ),
    ]
