# Generated by Django 2.1.3 on 2018-11-19 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0020_auto_20181119_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='hours',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='end_time',
            field=models.TimeField(default=datetime.time(1, 0), verbose_name='End time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(default=datetime.time(1, 0), verbose_name='Start time'),
            preserve_default=False,
        ),
    ]
