# Generated by Django 2.1.3 on 2018-11-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0024_auto_20181119_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='date',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='end',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
