# Generated by Django 2.1.3 on 2018-11-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0025_auto_20181119_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='week',
            field=models.IntegerField(default=47, verbose_name='working week'),
            preserve_default=False,
        ),
    ]
