# Generated by Django 2.1.3 on 2018-11-26 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0026_timesheet_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='allDay',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='start',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
