# Generated by Django 2.1.3 on 2018-11-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0027_auto_20181126_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='working_hour',
            field=models.TimeField(default='08:30', verbose_name='Working time'),
            preserve_default=False,
        ),
    ]
