# Generated by Django 2.1.3 on 2018-11-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0028_timesheet_working_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='working_hour',
            field=models.TimeField(help_text='Format: HH:mm', verbose_name='Working time'),
        ),
    ]
