# Generated by Django 2.1.3 on 2018-11-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0030_auto_20181127_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='working_hour',
            field=models.FloatField(verbose_name='Working time'),
        ),
    ]
