# Generated by Django 2.1.3 on 2018-11-22 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128, verbose_name='Street')),
                ('npa', models.SmallIntegerField(verbose_name='NPA')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('canton', models.CharField(max_length=64, verbose_name='Canton')),
                ('phone', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('uuid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
