# Generated by Django 2.1.3 on 2018-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'pharmacies'},
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='fax',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
