# Generated by Django 2.1.3 on 2018-11-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20181122_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='fax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='npa',
            field=models.PositiveIntegerField(verbose_name='NPA'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
