# Generated by Django 2.1.3 on 2018-11-22 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20181122_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
