# Generated by Django 2.1.3 on 2018-11-15 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=64, verbose_name='Client')),
                ('priority', models.CharField(choices=[('l', 'Low'), ('n', 'Normal'), ('h', 'Hight'), ('c', 'Critical')], max_length=1, verbose_name='Priority')),
                ('category', models.CharField(choices=[('I', 'IT')], max_length=1, verbose_name='Category')),
                ('description_of_the_problem', models.TextField(verbose_name='Description of the problem')),
                ('followed', models.TextField(verbose_name='Followed')),
                ('solution', models.TextField(verbose_name='Solution')),
                ('status', models.CharField(choices=[('o', 'open'), ('s', 'Close: solved'), ('a', 'Close: abandon')], max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
