# Generated by Django 2.1.3 on 2018-11-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdesk',
            name='followed',
            field=models.TextField(blank=True, verbose_name='Followed'),
        ),
        migrations.AlterField(
            model_name='helpdesk',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Solution'),
        ),
    ]
