# Generated by Django 2.1.3 on 2018-11-23 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvement',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
